# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

[
{:name => "AALAND ISLANDS", :code => "AX", :long_code => "ALA", :number => "248"},
{:name => "AFGHANISTAN", :code => "AF", :long_code => "AFG", :number => "004"},
{:name => "ALBANIA", :code => "AL", :long_code => "ALB", :number => "008" },
{:name => "ALGERIA", :code => "DZ", :long_code => "DZA", :number => "012"},
{:name => "AMERICAN SAMOA", :code => "AS", :long_code => "ASM", :number => "016"},
{:name => "ANDORRA", :code => "AD", :long_code => "AND", :number => "020"},
{:name => "ANGOLA", :code => "AO", :long_code => "AGO", :number => "024"},
{:name => "ANGUILLA", :code => "AI", :long_code => "AIA", :number => "660"},
{:name => "ANTARCTICA", :code => "AQ", :long_code => "ATA", :number => "010"},
{:name => "ANTIGUA AND BARBUDA", :code => "AG", :long_code => "ATG", :number => "028"},
{:name => "ARGENTINA", :code => "AR", :long_code => "ARG", :number => "032"},
{:name => "ARMENIA", :code => "AM", :long_code => "ARM", :number => "051"},
{:name => "ARUBA", :code => "AW", :long_code => "ABW", :number => "533"},
{:name => "AUSTRALIA", :code => "AU", :long_code => "AUS", :number => "036"},
{:name => "AUSTRIA", :code => "AT", :long_code => "AUT", :number => "040"},
{:name => "AZERBAIJAN", :code => "AZ", :long_code => "AZE", :number => "031"},
{:name => "BAHAMAS", :code => "BS", :long_code => "BHS", :number => "044"},
{:name => "BAHRAIN", :code => "BH", :long_code => "BHR", :number => "048"},
{:name => "BANGLADESH", :code => "BD", :long_code => "BGD", :number => "050"},
{:name => "BARBADOS", :code => "BB", :long_code => "BRB", :number => "052"},
{:name => "BELARUS", :code => "BY", :long_code => "BLR", :number => "112"},
{:name => "BELGIUM", :code => "BE", :long_code => "BEL", :number => "056"},
{:name => "BELIZE", :code => "BZ", :long_code => "BLZ", :number => "084"},
{:name => "BENIN", :code => "BJ", :long_code => "BEN", :number => "204"},
{:name => "BERMUDA", :code => "BM", :long_code => "BMU", :number => "060"},
{:name => "BHUTAN", :code => "BT", :long_code => "BTN", :number => "064"},
{:name => "BOLIVIA", :code => "BO", :long_code => "BOL", :number => "068"},
{:name => "BOSNIA AND HERZEGOWINA", :code => "BA", :long_code => "BIH", :number => "070"},
{:name => "BOTSWANA", :code => "BW", :long_code => "BWA", :number => "072"},
{:name => "BOUVET ISLAND", :code => "BV", :long_code => "BVT", :number => "074"},
{:name => "BRAZIL", :code => "BR", :long_code => "BRA", :number => "076"},
{:name => "BRITISH INDIAN OCEAN TERRITORY", :code => "IO", :long_code => "IOT", :number => "086"},
{:name => "BRUNEI DARUSSALAM", :code => "BN", :long_code => "BRN", :number => "096"},
{:name => "BULGARIA", :code => "BG", :long_code => "BGR", :number => "100"},
{:name => "BURKINA FASO", :code => "BF", :long_code => "BFA", :number => "854"},
{:name => "BURUNDI", :code => "BI", :long_code => "BDI", :number => "108"},
{:name => "CAMBODIA", :code => "KH", :long_code => "KHM", :number => "116"},
{:name => "CAMEROON", :code => "CM", :long_code => "CMR", :number => "120"},
{:name => "CANADA", :code => "CA", :long_code => "CAN", :number => "124"},
{:name => "CAPE VERDE", :code => "CV", :long_code => "CPV", :number => "132"},
{:name => "CAYMAN ISLANDS", :code => "KY", :long_code => "CYM", :number => "136"},
{:name => "CENTRAL AFRICAN REPUBLIC", :code => "CF", :long_code => "CAF", :number => "140"},
{:name => "CHAD", :code => "TD", :long_code => "TCD", :number => "148"},
{:name => "CHILE", :code => "CL", :long_code => "CHL", :number => "152"},
{:name => "CHINA", :code => "CN", :long_code => "CHN", :number => "156"},
{:name => "CHRISTMAS ISLAND", :code => "CX", :long_code => "CXR", :number => "162"},
{:name => "COCOS ISLANDS", :code => "CC", :long_code => "CCK", :number => "166"},
{:name => "COLOMBIA", :code => "CO", :long_code => "COL", :number => "170"},
{:name => "COMOROS", :code => "KM", :long_code => "COM", :number => "174"},
{:name => "CONGO, Democratic Republic of", :code => "CD", :long_code => "COD", :number => "180"},
{:name => "CONGO, Republic of", :code => "CK", :long_code => "COG", :number => "178"},
{:name => "COOK ISLANDS", :code => "CK", :long_code => "COK", :number => "184"},
{:name => "COSTA RICA", :code => "CR", :long_code => "CRI", :number => "188"},
{:name => "COTE D'IVOIRE", :code => "CI", :long_code => "CIV", :number => "384"},
{:name => "CROATIA", :code => "HR", :long_code => "HRV", :number => "191"},
{:name => "CUBA", :code => "CU", :long_code => "CUB", :number => "192"},
{:name => "CYPRUS", :code => "CY", :long_code => "CYP", :number => "196"},
{:name => "CZECH REPUBLIC", :code => "CZ", :long_code => "CZE", :number => "203"},
{:name => "DENMARK", :code => "DK", :long_code => "DNK", :number => "208"},
{:name => "DJIBOUTI", :code => "DJ", :long_code => "DJI", :number => "262"},
{:name => "DOMINICA", :code => "DM", :long_code => "DMA", :number => "212"},
{:name => "DOMINICAN REPUBLIC", :code => "DO", :long_code => "DOM", :number => "214"},
{:name => "ECUADOR", :code => "EC", :long_code => "ECU", :number => "218"},
{:name => "EGYPT", :code => "EG", :long_code => "EGY", :number => "818"},
{:name => "EL SALVADOR", :code => "SV", :long_code => "SLV", :number => "222"},
{:name => "EQUATORIAL GUINEA", :code => "GQ", :long_code => "GNQ", :number => "226"},
{:name => "ERITREA", :code => "ER", :long_code => "ERI", :number => "232"},
{:name => "ESTONIA", :code => "EE", :long_code => "EST", :number => "233"},
{:name => "ETHIOPIA", :code => "ET", :long_code => "ETH", :number => "231"},
{:name => "FALKLAND ISLANDS", :code => "FK", :long_code => "FLK", :number => "238"},
{:name => "FAROE ISLANDS", :code => "FO", :long_code => "FRO", :number => "234"},
{:name => "FIJI", :code => "FJ", :long_code => "FJI", :number => "242"},
{:name => "FINLAND", :code => "FI", :long_code => "FIN", :number => "246"},
{:name => "FRANCE", :code => "FR", :long_code => "FRA", :number => "250"},
{:name => "FRENCH GUIANA", :code => "GF", :long_code => "GUF", :number => "254"},
{:name => "FRENCH POLYNESIA", :code => "PF", :long_code => "PYF", :number => "258"},
{:name => "FRENCH SOUTHERN TERRITORIES", :code => "TF", :long_code => "ATF", :number => "260"},
{:name => "GABON", :code => "GA", :long_code => "GAB", :number => "266"},
{:name => "GAMBIA", :code => "GM", :long_code => "GMB", :number => "270"},
{:name => "GEORGIA", :code => "GE", :long_code => "GEO", :number => "268"},
{:name => "GERMANY", :code => "DE", :long_code => "DEU", :number => "276"},
{:name => "GHANA", :code => "GH", :long_code => "GHA", :number => "288"},
{:name => "GIBRALTAR", :code => "GI", :long_code => "GIB", :number => "292"},
{:name => "GREECE", :code => "GR", :long_code => "GRC", :number => "300"},
{:name => "GREENLAND", :code => "GL", :long_code => "GRL", :number => "304"},
{:name => "GRENADA", :code => "GD", :long_code => "GRD", :number => "308"},
{:name => "GUADELOUPE", :code => "GP", :long_code => "GLP", :number => "312"},
{:name => "GUAM", :code => "GU", :long_code => "GUM", :number => "316"},
{:name => "GUATEMALA", :code => "GT", :long_code => "GTM", :number => "320"},
{:name => "GUINEA", :code => "GN", :long_code => "GIN", :number => "324"},
{:name => "GUINEA-BISSAU", :code => "GW", :long_code => "GNB", :number => "624"},
{:name => "GUYANA", :code => "GY", :long_code => "GUY", :number => "328"},
{:name => "HAITI", :code => "HT", :long_code => "HTI", :number => "332"},
{:name => "HEARD AND MC DONALD ISLANDS", :code => "HM", :long_code => "HMD", :number => "334"},
{:name => "HONDURAS", :code => "HN", :long_code => "HND", :number => "340"},
{:name => "HONG KONG", :code => "HK", :long_code => "HKG", :number => "344"},
{:name => "HUNGARY", :code => "HU", :long_code => "HUN", :number => "348"},
{:name => "ICELAND", :code => "IS", :long_code => "ISL", :number => "352"},
{:name => "INDIA", :code => "IN", :long_code => "IND", :number => "356"},
{:name => "INDONESIA", :code => "ID", :long_code => "IDN", :number => "360"},
{:name => "IRAN ", :code => "IR", :long_code => "IRN", :number => "364"},
{:name => "IRAQ", :code => "IQ", :long_code => "IRQ", :number => "368"},
{:name => "IRELAND", :code => "IE", :long_code => "IRL", :number => "372"},
{:name => "ISRAEL", :code => "IL", :long_code => "ISR", :number => "376"},
{:name => "ITALY", :code => "IT", :long_code => "ITA", :number => "380"},
{:name => "JAMAICA", :code => "JM", :long_code => "JAM", :number => "388"},
{:name => "JAPAN", :code => "JP", :long_code => "JPN", :number => "392"},
{:name => "JORDAN", :code => "JO", :long_code => "JOR", :number => "400"},
{:name => "KAZAKHSTAN", :code => "KZ", :long_code => "KAZ", :number => "398"},
{:name => "KENYA", :code => "KE", :long_code => "KEN", :number => "404"},
{:name => "KIRIBATI", :code => "KI", :long_code => "KIR", :number => "296"},
{:name => "KOREA", :code => "KP", :long_code => "PRK", :number => "408"},
{:name => "REPUBLIC OF KOREA", :code => "KR", :long_code => "KOR", :number => "410"},
{:name => "KUWAIT", :code => "KW", :long_code => "KWT", :number => "414"},
{:name => "KYRGYZSTAN", :code => "KG", :long_code => "KGZ", :number => "417"},
{:name => "LAOS", :code => "LA", :long_code => "LAO", :number => "418"},
{:name => "LATVIA", :code => "LV", :long_code => "LVA", :number => "428"},
{:name => "LEBANON", :code => "LB", :long_code => "LBN", :number => "422"},
{:name => "LESOTHO", :code => "LS", :long_code => "LSO", :number => "426"},
{:name => "LIBERIA", :code => "LR", :long_code => "LBR", :number => "430"},
{:name => "LIBYAN ARAB JAMAHIRIYA", :code => "LY", :long_code => "LBY", :number => "434"},
{:name => "LIECHTENSTEIN", :code => "LI", :long_code => "LIE", :number => "438"},
{:name => "LITHUANIA", :code => "LT", :long_code => "LTU", :number => "440"},
{:name => "LUXEMBOURG", :code => "LU", :long_code => "LUX", :number => "442"},
{:name => "MACAU", :code => "MO", :long_code => "MAC", :number => "446"},
{:name => "MACEDONIA", :code => "MK", :long_code => "MKD", :number => "807"},
{:name => "MADAGASCAR", :code => "MG", :long_code => "MDG", :number => "450"},
{:name => "MALAWI", :code => "MW", :long_code => "MWI", :number => "454"},
{:name => "MALAYSIA", :code => "MY", :long_code => "MYS", :number => "458"},
{:name => "MALDIVES", :code => "MV", :long_code => "MDV", :number => "462"},
{:name => "MALI", :code => "ML", :long_code => "MLI", :number => "466"},
{:name => "MALTA", :code => "MT", :long_code => "MLT", :number => "470"},
{:name => "MARSHALL ISLANDS", :code => "MH", :long_code => "MHL", :number => "584"},
{:name => "MARTINIQUE", :code => "MQ", :long_code => "MTQ", :number => "474"},
{:name => "MAURITANIA", :code => "MR", :long_code => "MRT", :number => "478"},
{:name => "MAURITIUS", :code => "MU", :long_code => "MUS", :number => "480"},
{:name => "MAYOTTE", :code => "YT", :long_code => "MYT", :number => "175"},
{:name => "MEXICO", :code => "MX", :long_code => "MEX", :number => "484"},
{:name => "MICRONESIA", :code => "FM", :long_code => "FSM", :number => "583"},
{:name => "MOLDOVA", :code => "MD", :long_code => "MDA", :number => "498"},
{:name => "MONACO", :code => "MC", :long_code => "MCO", :number => "492"},
{:name => "MONGOLIA", :code => "MN", :long_code => "MNG", :number => "496"},
{:name => "MONTSERRAT", :code => "MS", :long_code => "MSR", :number => "500"},
{:name => "MOROCCO", :code => "MA", :long_code => "MAR", :number => "504"},
{:name => "MOZAMBIQUE", :code => "MZ", :long_code => "MOZ", :number => "508"},
{:name => "MYANMAR", :code => "MM", :long_code => "MMR", :number => "104"},
{:name => "NAMIBIA", :code => "NA", :long_code => "NAM", :number => "516"},
{:name => "NAURU", :code => "NR", :long_code => "NRU", :number => "520"},
{:name => "NEPAL", :code => "NP", :long_code => "NPL", :number => "524"},
{:name => "NETHERLANDS", :code => "NL", :long_code => "NLD", :number => "528"},
{:name => "NETHERLANDS ANTILLES", :code => "AN", :long_code => "ANT", :number => "530"},
{:name => "NEW CALEDONIA", :code => "NC", :long_code => "NCL", :number => "540"},
{:name => "NEW ZEALAND", :code => "NZ", :long_code => "NZL", :number => "554"},
{:name => "NICARAGUA", :code => "NI", :long_code => "NIC", :number => "558"},
{:name => "NIGER", :code => "NE", :long_code => "NER", :number => "562"},
{:name => "NIGERIA", :code => "NG", :long_code => "NGA", :number => "566"},
{:name => "NIUE", :code => "NU", :long_code => "NIU", :number => "570"},
{:name => "NORFOLK ISLAND", :code => "NF", :long_code => "NFK", :number => "574"},
{:name => "NORTHERN MARIANA ISLANDS", :code => "MP", :long_code => "MNP", :number => "580"},
{:name => "NORWAY", :code => "NO", :long_code => "NOR", :number => "578"},
{:name => "OMAN", :code => "OM", :long_code => "OMN", :number => "512"},
{:name => "PAKISTAN", :code => "PK", :long_code => "PAK", :number => "586"},
{:name => "PALAU", :code => "PW", :long_code => "PLW", :number => "585"},
{:name => "PALESTINA", :code => "PS", :long_code => "PSE", :number => "275"},
{:name => "PANAMA", :code => "PA", :long_code => "PAN", :number => "591"},
{:name => "PAPUA NEW GUINEA", :code => "PG", :long_code => "PNG", :number => "598"},
{:name => "PARAGUAY", :code => "PY", :long_code => "PRY", :number => "600"},
{:name => "PERU", :code => "PE", :long_code => "PER", :number => "604"},
{:name => "PHILIPPINES", :code => "PH", :long_code => "PHL", :number => "608"},
{:name => "PITCAIRN", :code => "PN", :long_code => "PCN", :number => "612"},
{:name => "POLAND", :code => "PL", :long_code => "POL", :number => "616"},
{:name => "PORTUGAL", :code => "PT", :long_code => "PRT", :number => "620"},
{:name => "PUERTO RICO", :code => "PR", :long_code => "PRI", :number => "630"},
{:name => "QATAR", :code => "QA", :long_code => "QAT", :number => "634"},
{:name => "REUNION", :code => "RE", :long_code => "REU", :number => "638"},
{:name => "ROMANIA", :code => "RO", :long_code => "ROU", :number => "642"},
{:name => "RUSSIAN FEDERATION", :code => "RU", :long_code => "RUS", :number => "643"},
{:name => "RWANDA", :code => "RW", :long_code => "RWA", :number => "646"},
{:name => "SAINT HELENA", :code => "SH", :long_code => "SHN", :number => "654"},
{:name => "SAINT KITTS AND NEVIS", :code => "KN", :long_code => "KNA", :number => "659"},
{:name => "SAINT LUCIA", :code => "LC", :long_code => "LCA", :number => "662"},
{:name => "SAINT PIERRE AND MIQUELON", :code => "PM", :long_code => "SPM", :number => "666"},
{:name => "SAINT VINCENT AND THE GRENADINES", :code => "VC", :long_code => "VCT", :number => "670"},
{:name => "SAMOA", :code => "WS", :long_code => "WSM", :number => "882"},
{:name => "SAN MARINO", :code => "SM", :long_code => "SMR", :number => "674"},
{:name => "SAO TOME AND PRINCIPE", :code => "ST", :long_code => "STP", :number => "678"},
{:name => "SAUDI ARABIA", :code => "SA", :long_code => "SAU", :number => "682"},
{:name => "SENEGAL", :code => "SN", :long_code => "SEN", :number => "686"},
{:name => "SERBIA AND MONTENEGRO", :code => "CS", :long_code => "SCG", :number => "891"},
{:name => "SEYCHELLES", :code => "SC", :long_code => "SYC", :number => "690"},
{:name => "SIERRA LEONE", :code => "SL", :long_code => "SLE", :number => "694"},
{:name => "SINGAPORE", :code => "SG", :long_code => "SGP", :number => "702"},
{:name => "SLOVAKIA", :code => "SK", :long_code => "SVK", :number => "703"},
{:name => "SLOVENIA", :code => "SI", :long_code => "SVN", :number => "705"},
{:name => "SOLOMON ISLANDS", :code => "SB", :long_code => "SLB", :number => "090"},
{:name => "SOMALIA", :code => "SO", :long_code => "SOM", :number => "706"},
{:name => "SOUTH AFRICA", :code => "ZA", :long_code => "ZAF", :number => "710"},
{:name => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", :code => "GS", :long_code => "SGS", :number => "239"},
{:name => "SPAIN", :code => "ES", :long_code => "ESP", :number => "724"},
{:name => "SRI LANKA", :code => "LK", :long_code => "LKA", :number => "144"},
{:name => "SUDAN", :code => "SD", :long_code => "SDN", :number => "736"},
{:name => "SURINAME", :code => "SR", :long_code => "SUR", :number => "740"},
{:name => "SVALBARD AND JAN MAYEN ISLANDS", :code => "SJ", :long_code => "SJM", :number => "744"},
{:name => "SWAZILAND", :code => "SZ", :long_code => "SWZ", :number => "748"},
{:name => "SWEDEN", :code => "SE", :long_code => "SWE", :number => "752"},
{:name => "SWITZERLAND", :code => "CH", :long_code => "CHE", :number => "756"},
{:name => "SYRIAN ARAB REPUBLIC", :code => "SY", :long_code => "SYR", :number => "760"},
{:name => "TAIWAN", :code => "TW", :long_code => "TWN", :number => "158"},
{:name => "TAJIKISTAN", :code => "TJ", :long_code => "TJK", :number => "762"},
{:name => "TANZANIA", :code => "TZ", :long_code => "TZA", :number => "834"},
{:name => "THAILAND", :code => "TH", :long_code => "THA", :number => "764"},
{:name => "TIMOR-LESTE", :code => "TL", :long_code => "TLS", :number => "626"},
{:name => "TOGO", :code => "TG", :long_code => "TGO", :number => "768"},
{:name => "TOKELAU", :code => "TK", :long_code => "TKL", :number => "772"},
{:name => "TONGA", :code => "TO", :long_code => "TON", :number => "776"},
{:name => "TRINIDAD AND TOBAGO", :code => "TT", :long_code => "TTO", :number => "780"},
{:name => "TUNISIA", :code => "TN", :long_code => "TUN", :number => "788"},
{:name => "TURKEY", :code => "TR", :long_code => "TUR", :number => "792"},
{:name => "TURKMENISTAN", :code => "TM", :long_code => "TKM", :number => "795"},
{:name => "TURKS AND CAICOS ISLANDS", :code => "TC", :long_code => "TCA", :number => "796"},
{:name => "TUVALU", :code => "TV", :long_code => "TUV", :number => "798"},
{:name => "UGANDA", :code => "UG", :long_code => "UGA", :number => "800"},
{:name => "UKRAINE", :code => "UA", :long_code => "UKR", :number => "804"},
{:name => "UNITED ARAB EMIRATES", :code => "AE", :long_code => "ARE", :number => "784"},
{:name => "UNITED KINGDOM", :code => "GB", :long_code => "GBR", :number => "826"},
{:name => "UNITED STATES", :code => "US", :long_code => "USA", :number => "840"},
{:name => "UNITED STATES MINOR OUTLYING ISLANDS", :code => "UM", :long_code => "UMI", :number => "581"},
{:name => "URUGUAY", :code => "UY", :long_code => "URY", :number => "858"},
{:name => "UZBEKISTAN", :code => "UZ", :long_code => "UZB", :number => "860"},
{:name => "VANUATU", :code => "VU", :long_code => "VUT", :number => "548"},
{:name => "VATICAN", :code => "VA", :long_code => "VAT", :number => "336"},
{:name => "VENEZUELA", :code => "VE", :long_code => "VEN", :number => "862"},
{:name => "VIET NAM", :code => "VN", :long_code => "VNM", :number => "704"},
{:name => "BRITISH VIRGIN ISLANDS", :code => "VG", :long_code => "VGB", :number => "092"},
{:name => "U.S. VIRGIN ISLANDS", :code => "VI", :long_code => "VIR", :number => "850"},
{:name => "WALLIS AND FUTUNA ISLANDS", :code => "WF", :long_code => "WLF", :number => "876"},
{:name => "WESTERN SAHARA", :code => "EH", :long_code => "ESH", :number => "732"},
{:name => "YEMEN", :code => "YE", :long_code => "YEM", :number => "887"},
{:name => "ZAMBIA", :code => "ZM", :long_code => "ZMB", :number => "894"},
{:name => "ZIMBABWE", :code => "ZW", :long_code => "ZWE", :number => "716"},
].each do |h|
	country = Country.where( {name: /#{h[:name]}/i}).first || Country.new
	country.update_attributes(h.inject({}){|memo, k| memo[k.first] = k.last.downcase; memo })
end






