development:
  consumer_key:  <%= ENV['API_FACEBOOK_KEY'] %> 
  consumer_secret: <%= ENV['API_FACEBOOK_SECRET'] %>
production:
  consumer_key: <%= ENV['API_FACEBOOK_KEY'] %> 
  consumer_secret: <%= ENV['API_FACEBOOK_SECRET'] %>