development:
  consumer_key: xd8I0gXbjmuzErUfJ6ZUZg
  consumer_secret: KdERl9MuZtIAmllAC1NML3x9HRrnZF8DczivgjhZfo
production:
  consumer_key: shfFZtYCp07HugqviwbVdg
  consumer_secret: VHEGMojABZR6noEkTJPTp3Yxbd8ENDiYfIuO1skM