development:
  consumer_key: <%= ENV['API_TWITTER_KEY'] %> 
  consumer_secret: <%= ENV['API_TWITTER_SECRET'] %> 
production:
  consumer_key: <%= ENV['API_TWITTER_KEY'] %> 
  consumer_secret: <%= ENV['API_TWITTER_SECRET'] %> 